include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
    camel_case_types: error
    camel_case_extensions: error
    non_constant_identifier_names: error
    constant_identifier_names: error
    directives_ordering: error
    lines_longer_than_80_chars: error
    curly_braces_in_flow_control_structures: error
    avoid_dynamic_calls: error
    avoid_empty_else: error
    avoid_returning_null_for_future: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    collection_methods_unrelated_type: error
    comment_references: error
    control_flow_in_finally: error
    deprecated_member_use_from_same_package: error
    require_trailing_commas: error

linter:
  rules:
    avoid_print: true
    camel_case_types: true
    camel_case_extensions: true
    library_prefixes: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    directives_ordering: true
    lines_longer_than_80_chars: true
    curly_braces_in_flow_control_structures: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    collection_methods_unrelated_type: true
    comment_references: true
    control_flow_in_finally: true
    deprecated_member_use_from_same_package: true
    require_trailing_commas: true
    prefer_relative_imports: true
