name: flutter_skeleton
description: Flutter Skeleton

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  easy_localization: ^3.0.3
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  sizer: ^2.0.15
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  pretty_dio_logger: ^1.3.1
  git_hooks: ^1.0.1
  connectivity_plus: ^5.0.2
  easy_stepper: ^0.8.5
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  equatable: ^2.0.5
  flash: ^3.1.0
  dropdown_button2: ^2.3.8
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^22.2.5
  carousel_slider: ^4.2.1
 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/
    - bin/
fonts:
  - family: "Noto Sans JP"
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/OpenSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/OpenSans-SemiBold.ttf
        weight: 600